### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by TangYiChing** [EureKaZhu/DiffAffinity#2]
Hi, can you tell me how to fix this?

I followed the instructions but got an error at the step: **GEOMSTATS_BACKEND=jax pip install -e geomstats**

here's the error msg:error: subprocess-exited-with-error
  
 Obtaining file:///geomstats
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/geomstats/setup.py", line 9, in <module>
          geomstats = runpy.run_path(os.path.join(base_dir, "geomstats", "__init__.py"))
        File "/opt/conda/envs/DiffAffinity/lib/python3.9/runpy.py", line 288, in run_path
          return _run_module_code(code, init_globals, run_name,
        File "/opt/conda/envs/DiffAffinity/lib/python3.9/runpy.py", line 97, in _run_module_code
          _run_code(code, mod_globals, init_globals,
        File "/opt/conda/envs/DiffAffinity/lib/python3.9/runpy.py", line 87, in _run_code
          exec(code, run_globals)
        File "/geomstats/geomstats/__init__.py", line 3, in <module>
          import geomstats._backend
        File "/geomstats/geomstats/__init__.py", line 5, in <module>
          import geomstats.geometry.discrete_curves
        File "/geomstats/geomstats/geometry/discrete_curves.py", line 7, in <module>
          import geomstats.backend as gs
        File "/geomstats/geomstats/_backend/__init__.py", line 252, in load_module
          module = self._create_backend_module(_BACKEND)
        File "/geomstats/geomstats/_backend/__init__.py", line 190, in _create_backend_module
          backend = self._import_backend(backend_name)
       /geomstats/geomstats/_backend/__init__.py", line 184, in _import_backend
          from geomstats._backend import jax as backend
        File "/geomstats/geomstats/_backend/jax/__init__.py", line 5, in <module>
          import jax.numpy as np
      ModuleNotFoundError: No module named 'jax'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by TianZhuAI4S** [comment]
You can refer to the installation of riemannian score based generative model (https://github.com/oxcsml/riemannian-score-sde/)
